### ISSUE TITLE
Code coverage and pep8

### ISSUE THREAD

**Issue by LTKills** [LTKills/heroes_build_scrapper#39]
Set up code coverage, best practices, pep8. Accept suggestions on this

**Comment by guillearch** [comment]
I improved PEP8 compliance on PR #43.

Accordining to Flake8, there is still room for improvement:
```
./docs/conf.py:134:80: E501 line too long (88 > 79 characters)
./docs/conf.py:144:80: E501 line too long (80 > 79 characters)
./docs/conf.py:155:80: E501 line too long (80 > 79 characters)
./src/heroes_build_scrapper/data.py:5:1: F401 'requests' imported but unused
./src/heroes_build_scrapper/data.py:6:1: F401 'bs4.BeautifulSoup' imported but unused
./src/heroes_build_scrapper/utils.py:42:22: F821 undefined name 'load_builds'
./src/heroes_build_scrapper/scrapping.py:3:1: F401 'requests' imported but unused
./src/heroes_build_scrapper/scrapping.py:4:1: F401 'bs4.BeautifulSoup' imported but unused
./src/heroes_build_scrapper/scrapping.py:5:1: F401 '.utils.print_build' imported but unused
./src/heroes_build_scrapper/__init__.py:3:1: F401 '.data.update_all_builds' imported but unused
./src/heroes_build_scrapper/__init__.py:4:1: F401 '.scrapping.update_hero_builds' imported but unused
./src/heroes_build_scrapper/__init__.py:4:1: F401 '.scrapping.load_builds' imported but unused
./src/heroes_build_scrapper/__init__.py:5:1: F401 '.utils.print_hero_builds' imported but unused
./src/heroes_build_scrapper/__init__.py:5:1: F401 '.utils.get_heroes_list' imported but unused
./src/heroes_build_scrapper/__init__.py:5:1: F401 '.utils.print_build' imported but unused

```
I also suggest to rename `class_` to `hero_class` or `role` to avoid the clash with the reserved keyword `class`.

**Comment by LTKills** [comment]
Be sure to always ask to be assigned to an issue before starting to do any code. As nobody requested to be assigned before, I'm assigning you. Here this may not be such a necessary thing to do, but in more flooded repos it can be reason enough to close your PR

**Comment by LTKills** [comment]
Also, can you specify in which file should `class` be renamed?

**Comment by guillearch** [comment]
Sorry for the inconvenience!
I've just realised that you're using `class_` as an argument (files data.py and scrapping.py), so it's OK. Everything else seems good too regarding comment and naming conventions.

**Comment by LTKills** [comment]
Oh yeah that's actually a [Beautiful Soup thing](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#searching-by-css-class)
